//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qlxm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThueXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThueXe()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int IDThue { get; set; }
        public int IDKhachHang { get; set; }
        public int IDNguoi { get; set; }
        public int IDXe { get; set; }
        public System.DateTime NgayThue { get; set; }
        public System.DateTime NgayTra { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Nguoi Nguoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
