//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qlxm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.ThueXes = new HashSet<ThueXe>();
        }
    
        public int IDXe { get; set; }
        public string TenXe { get; set; }
        public string NhaSanXuat { get; set; }
        public int SoDangKi { get; set; }
        public string BienSo { get; set; }
        public string PhanKhoi { get; set; }
        public string MauSac { get; set; }
        public int GiaThue { get; set; }
        public bool TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThueXe> ThueXes { get; set; }
    }
}
